name 'yum-sensu'
maintainer 'Chase Bolt'
maintainer_email 'chase.bolt@gmail.com'
license 'Apache 2.0'
description 'Installs and configures the sensu yum repository'
version '0.1.1'

source_url 'https://github.com/chasebolt/chef-yum-sensu'
issues_url 'https://github.com/chasebolt/chef-yum-sensu/issues'

supports 'amazon'
supports 'centos'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'scientific'
